"""add order buy

Revision ID: 0defb62e81ab
Revises: 531c0a0d039d
Create Date: 2025-05-27 17:31:36.582428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0defb62e81ab'
down_revision: Union[str, None] = '531c0a0d039d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Integer(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('vip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
