"""add Vip table

Revision ID: 531c0a0d039d
Revises: 83d3bca3e8d3
Create Date: 2025-05-26 15:30:50.338132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '531c0a0d039d'
down_revision: Union[str, None] = '83d3bca3e8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vip',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vip_id', sa.Integer(), nullable=False),
    sa.Column('cc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cc_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('notion_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weread_cookie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notion_page', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('vip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vip')
    # ### end Alembic commands ###
