"""fix user remove starttime

Revision ID: bd9c2a259648
Revises: e01416227431
Create Date: 2025-06-04 15:25:04.834458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bd9c2a259648'
down_revision: Union[str, None] = 'e01416227431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip', schema=None) as batch_op:
        batch_op.drop_column('vip_price')

    # ### end Alembic commands ###
